title: Cyber Autonomy Initiative
timezone: "America/New_York"

permalink: /blogposts/:title/

collections:
  datasets:
    output: true
    permalink: /data/:name/
  publications:
    output: false

defaults:
  - scope: { path: "", type: "posts" }
    values: { layout: "entry" }
  - scope: { path: "", type: "datasets" }
    values: { layout: "entry" }

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - claude_changelog.txt
  - vendor

plugins:
  - jekyll-sitemap
