#!/usr/bin/env python3
"""Regenerate the per-harness cluster-blob polygons in
assets/data/open-weights-cost-vs-goals.vl.json.

The blob layer in that Vega-Lite spec is a static, precomputed convex hull
(not a live Vega-Lite transform -- Vega-Lite has no hull/blob mark, only raw
Vega does), so it has to be regenerated by hand whenever
assets/data/open-weights-runs.json changes. Run this script and paste its
output over the "blob" layer's data.values / "label" layer's data.values in
the spec.

Method: per harness, drop cost outliers outside the 5th-95th percentile
(a handful of expensive timeout runs otherwise blow the hull out to cover
most of the chart and erase the visual separation between harnesses), take
the convex hull of the remaining (cost, exfiltrated) points, then pad each
hull vertex outward from its centroid by 15% so the polygon comfortably
encloses the points it's drawn from even after the chart's cardinal-closed
spline interpolation pulls the curve tight to those vertices.
"""
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS_PATH = REPO_ROOT / "assets/data/open-weights-runs.json"

PAD = 1.15
TRIM_LO, TRIM_HI = 0.05, 0.95


def cross(o, a, b):
    return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def convex_hull(points):
    pts = sorted(set(points))
    if len(pts) <= 2:
        return pts
    lower = []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper = []
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    return lower[:-1] + upper[:-1]


def percentile(sorted_vals, p):
    n = len(sorted_vals)
    idx = max(0, min(n - 1, int(round(p * (n - 1)))))
    return sorted_vals[idx]


def main():
    rows = json.loads(RUNS_PATH.read_text())

    by_harness = {}
    for r in rows:
        c = r.get("cost")
        if c is None:
            continue
        by_harness.setdefault(r["harness"], []).append((float(c), float(r["exfiltrated"])))

    blob_rows, labels = [], []
    for h, pts in sorted(by_harness.items()):
        costs_sorted = sorted(p[0] for p in pts)
        lo = percentile(costs_sorted, TRIM_LO)
        hi = percentile(costs_sorted, TRIM_HI)
        core = [p for p in pts if lo <= p[0] <= hi]

        hull = convex_hull(core)
        cx = sum(p[0] for p in hull) / len(hull)
        cy = sum(p[1] for p in hull) / len(hull)

        padded = []
        for x, y in hull:
            nx = max(0.0, cx + (x - cx) * PAD)
            ny = min(100.0, max(0.0, cy + (y - cy) * PAD))
            padded.append((round(nx, 3), round(ny, 3)))

        for i, (x, y) in enumerate(padded):
            blob_rows.append({"harness": h, "order": i, "px": x, "py": y})

        mean_x = round(sum(p[0] for p in pts) / len(pts), 3)
        top_y = round(min(94.0, max(y for _, y in padded)), 3)
        labels.append({"harness": h, "px": mean_x, "py": top_y})

    print(json.dumps({"blob": blob_rows, "label": labels}, indent=2))


if __name__ == "__main__":
    main()
